#!/bin/zsh

dir=mp4
suf=mp4

for cate in 'rrj' 'hrs'
do
    for entry in `find $cate -name "*.m3u8"`
    do
        input=$entry
        output=$cate/$dir/${${entry##*/}%%.*}.$suf
        echo $input '->' $output
        ffmpeg -y -i $input $output
    done
done
